services:
  mssql:
    # https://mcr.microsoft.com/artifact/mar/mssql/server/about
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      interconnect:
        aliases:
          - sqlserver
    ports:
      - 1433:1433
    restart: no
    secrets:
      - db_password
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD_FILE=/run/secrets/db_password
      - MSSQL_PID=Express
      - MSSQL_LCID=1041
      - MSSQL_COLLATION=Japanese_CI_AS
      - TZ="Asia/Tokyo"
    volumes:
      - mssql-data:/var/opt/mssql
      # use custom initdb.d with MSSQL_SA_PASSWORD_FILE.
      - ./mssql/run_custom_setup.sh:/opt/mssql/bin/run_custom_setup.sh
      - ./mssql/initdb.d:/mssql-server-setup-scripts.d

  pgsql:
    # https://hub.docker.com/_/postgres
    image: postgres:18-alpine
    networks:
      interconnect:
        aliases:
          - postgres
    ports:
      - 5432:5432
    restart: no
    secrets:
      - db_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --no-locale"
      TZ: "Asia/Tokyo"
    volumes:
      - pgsql-data:/var/lib/postgresql
      - ./pgsql/initdb.d:/docker-entrypoint-initdb.d

secrets:
   db_password:
     file: ../.db_password.txt

volumes:
  mssql-data:
  pgsql-data:

networks:
  interconnect:
    driver: bridge
